# -*- coding: utf-8 -*-

import base64
from datetime import datetime
from jinja2 import Template, Environment, sandbox
from markupsafe import Markup

from odoo import api, fields, models, _
from odoo.exceptions import UserError, ValidationError
from odoo.tools.safe_eval import safe_eval


class DocumentGenerated(models.Model):
    """Generated Document Model for storing documents created from templates."""
    
    _name = 'document.generated'
    _description = 'Generated Document'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'create_date desc, id desc'
    
    # Basic Information
    name = fields.Char(
        string='Document Name',
        required=True,
        tracking=True,
        help='Name of the generated document'
    )
    
    # Template Reference
    template_id = fields.Many2one(
        comodel_name='document.template',
        string='Template Used',
        required=True,
        ondelete='restrict',
        tracking=True,
        help='Template used to generate this document'
    )
    
    template_type = fields.Selection(
        string='Document Type',
        related='template_id.template_type',
        store=True,
        readonly=True
    )
    
    # Content
    html_content = fields.Html(
        string='Document Content',
        required=True,
        sanitize_attributes=False,
        sanitize_form=False,
        help='HTML content of the generated document (editable)'
    )
    
    # Related Record
    res_model = fields.Char(
        string='Related Model',
        help='Technical name of the related model'
    )
    
    res_id = fields.Integer(
        string='Related Record ID',
        help='ID of the related record'
    )
    
    res_name = fields.Char(
        string='Related Record',
        compute='_compute_res_name',
        store=True,
        help='Name of the related record'
    )
    
    # State
    state = fields.Selection(
        selection=[
            ('draft', 'Draft'),
            ('final', 'Final'),
            ('archived', 'Archived'),
        ],
        string='Status',
        default='draft',
        required=True,
        tracking=True,
        help='Status of the document'
    )
    
    # Generation Info
    generated_date = fields.Datetime(
        string='Generated Date',
        default=fields.Datetime.now,
        required=True,
        readonly=True,
        help='Date and time when document was generated'
    )
    
    generated_by = fields.Many2one(
        comodel_name='res.users',
        string='Generated By',
        default=lambda self: self.env.user,
        required=True,
        readonly=True,
        help='User who generated the document'
    )
    
    # PDF Attachment
    pdf_filename = fields.Char(
        string='PDF Filename',
        compute='_compute_pdf_filename'
    )
    
    pdf_file = fields.Binary(
        string='PDF File',
        attachment=True,
        readonly=True,
        help='Generated PDF file'
    )
    
    has_pdf = fields.Boolean(
        string='Has PDF',
        compute='_compute_has_pdf',
        store=True,
        help='Whether a PDF has been generated'
    )
    
    # Version Control
    version = fields.Integer(
        string='Version',
        default=1,
        readonly=True,
        help='Document version number'
    )
    
    parent_document_id = fields.Many2one(
        comodel_name='document.generated',
        string='Parent Document',
        ondelete='set null',
        help='Original document if this is a version'
    )
    
    version_ids = fields.One2many(
        comodel_name='document.generated',
        inverse_name='parent_document_id',
        string='Versions',
        help='All versions of this document'
    )
    
    version_count = fields.Integer(
        string='Version Count',
        compute='_compute_version_count'
    )
    
    # Company
    company_id = fields.Many2one(
        comodel_name='res.company',
        string='Company',
        default=lambda self: self.env.company,
        help='Company this document belongs to'
    )
    
    # Notes
    notes = fields.Text(
        string='Internal Notes',
        help='Internal notes about this document'
    )
    
    # Audit Trail
    create_uid = fields.Many2one(
        comodel_name='res.users',
        string='Created by',
        readonly=True
    )
    
    create_date = fields.Datetime(
        string='Created on',
        readonly=True
    )
    
    write_uid = fields.Many2one(
        comodel_name='res.users',
        string='Last Updated by',
        readonly=True
    )
    
    write_date = fields.Datetime(
        string='Last Updated on',
        readonly=True
    )
    
    @api.depends('name')
    def _compute_pdf_filename(self):
        """Compute PDF filename from document name."""
        for document in self:
            if document.name:
                # Clean filename and add .pdf extension
                safe_name = document.name.replace('/', '-').replace('\\', '-')
                document.pdf_filename = f"{safe_name}.pdf"
            else:
                document.pdf_filename = 'document.pdf'
    
    @api.depends('pdf_file')
    def _compute_has_pdf(self):
        """Check if PDF has been generated."""
        for document in self:
            document.has_pdf = bool(document.pdf_file)
    
    @api.depends('res_model', 'res_id')
    def _compute_res_name(self):
        """Compute the name of the related record."""
        for document in self:
            if document.res_model and document.res_id:
                try:
                    record = self.env[document.res_model].browse(document.res_id)
                    if record.exists():
                        document.res_name = record.display_name
                    else:
                        document.res_name = f'Deleted {document.res_model} #{document.res_id}'
                except Exception:
                    document.res_name = f'{document.res_model} #{document.res_id}'
            else:
                document.res_name = False
    
    @api.depends('version_ids')
    def _compute_version_count(self):
        """Compute number of versions."""
        for document in self:
            document.version_count = len(document.version_ids)
    
    @api.model
    def _render_template(self, template_content, record):
        """
        Render template content with Jinja2 using record data.
        
        Args:
            template_content (str): HTML template content with Jinja2 syntax
            record (recordset): Odoo record to use for rendering
            
        Returns:
            str: Rendered HTML content
        """
        if not record:
            raise UserError(_('No record provided for template rendering.'))
        
        # Prepare template context
        template_ctx = {
            'object': record,
            'user': self.env.user,
            'company': self.env.company,
            'today': fields.Date.today(),
            'now': fields.Datetime.now(),
            # Add utility functions
            'format_date': lambda date: fields.Date.to_string(date) if date else '',
            'format_datetime': lambda dt: fields.Datetime.to_string(dt) if dt else '',
            'format_amount': lambda amount, currency=None: f"{amount:,.2f}",
        }
        
        try:
            # Create Jinja2 environment with safe sandbox
            jinja_env = sandbox.SandboxedEnvironment(autoescape=True)
            jinja_template = jinja_env.from_string(template_content)
            
            # Render template
            rendered_content = jinja_template.render(template_ctx)
            
            return rendered_content
            
        except Exception as e:
            raise UserError(_(
                'Error rendering template: %s\n\n'
                'Please check your template syntax.'
            ) % str(e))
    
    def action_mark_as_final(self):
        """Mark document as final."""
        for document in self:
            if document.state != 'final':
                document.write({'state': 'final'})
                document.message_post(body=_('Document marked as final.'))
    
    def action_mark_as_draft(self):
        """Mark document as draft."""
        for document in self:
            if document.state != 'draft':
                document.write({'state': 'draft'})
                document.message_post(body=_('Document marked as draft.'))
    
    def action_archive_document(self):
        """Archive document."""
        for document in self:
            document.write({'state': 'archived', 'active': False})
            document.message_post(body=_('Document archived.'))
    
    def action_generate_pdf(self):
        """Generate PDF from HTML content."""
        self.ensure_one()
        
        # Get PDF report
        report = self.env.ref('document_template_manager.action_report_document_pdf')
        
        # Generate PDF
        pdf_content, _ = report._render_qweb_pdf([self.id])
        
        # Save PDF to field
        self.write({
            'pdf_file': base64.b64encode(pdf_content)
        })
        
        # Create attachment
        attachment = self.env['ir.attachment'].create({
            'name': self.pdf_filename,
            'type': 'binary',
            'datas': base64.b64encode(pdf_content),
            'res_model': self._name,
            'res_id': self.id,
            'mimetype': 'application/pdf',
        })
        
        self.message_post(
            body=_('PDF generated successfully.'),
            attachment_ids=[attachment.id]
        )
        
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Success'),
                'message': _('PDF generated successfully.'),
                'type': 'success',
                'sticky': False,
            }
        }
    
    def action_download_pdf(self):
        """Download generated PDF."""
        self.ensure_one()
        
        if not self.pdf_file:
            # Generate PDF if not exists
            self.action_generate_pdf()
        
        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/{self.id}?field=pdf_file&model=document.generated&filename_field=pdf_filename&download=true',
            'target': 'self',
        }
    
    def action_preview(self):
        """Preview document in browser."""
        self.ensure_one()
        
        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/document.generated/{self.id}/html_content',
            'target': 'new',
        }
    
    def action_duplicate(self):
        """Create a new version of the document."""
        self.ensure_one()
        
        # Get next version number
        if self.parent_document_id:
            parent = self.parent_document_id
        else:
            parent = self
        
        max_version = max([v.version for v in parent.version_ids] + [parent.version])
        new_version = max_version + 1
        
        # Create new version
        new_document = self.copy({
            'name': f'{self.name} (v{new_version})',
            'version': new_version,
            'parent_document_id': parent.id,
            'state': 'draft',
            'pdf_file': False,
        })
        
        self.message_post(
            body=_('New version created: <a href="#id=%s&model=document.generated">%s</a>') % (
                new_document.id, new_document.name
            )
        )
        
        return {
            'type': 'ir.actions.act_window',
            'res_model': 'document.generated',
            'res_id': new_document.id,
            'view_mode': 'form',
            'target': 'current',
        }
    
    def action_view_versions(self):
        """View all versions of this document."""
        self.ensure_one()
        
        if self.parent_document_id:
            parent = self.parent_document_id
        else:
            parent = self
        
        all_versions = parent | parent.version_ids
        
        return {
            'name': _('Document Versions'),
            'type': 'ir.actions.act_window',
            'res_model': 'document.generated',
            'view_mode': 'tree,form',
            'domain': [('id', 'in', all_versions.ids)],
            'context': {'create': False}
        }
    
    def action_send_email(self):
        """Send document as email with PDF attachment."""
        self.ensure_one()
        
        # Generate PDF if not exists
        if not self.pdf_file:
            self.action_generate_pdf()
        
        # Get email compose wizard
        template = self.env.ref('document_template_manager.email_template_send_document', raise_if_not_found=False)
        
        compose_form = self.env.ref('mail.email_compose_message_wizard_form', raise_if_not_found=False)
        
        ctx = {
            'default_model': 'document.generated',
            'default_res_ids': [self.id],
            'default_use_template': bool(template),
            'default_template_id': template.id if template else False,
            'default_composition_mode': 'comment',
            'force_email': True,
        }
        
        return {
            'name': _('Send Document'),
            'type': 'ir.actions.act_window',
            'view_mode': 'form',
            'res_model': 'mail.compose.message',
            'views': [(compose_form.id, 'form')],
            'view_id': compose_form.id,
            'target': 'new',
            'context': ctx,
        }
    
    def action_open_related_record(self):
        """Open the related record."""
        self.ensure_one()
        
        if not self.res_model or not self.res_id:
            raise UserError(_('No related record found.'))
        
        return {
            'type': 'ir.actions.act_window',
            'res_model': self.res_model,
            'res_id': self.res_id,
            'view_mode': 'form',
            'target': 'current',
        }
